Org.Carfh.Courseware/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lang;
using Org.Cafh.Courseware.Models.Courseware;
using Org.Cafh.Courseware.Models.Repositories;

namespace Org.Cafh.Courseware.Controllers
{
    public class CoursesController : Controller
    {

        private static CoursewareDataContext _context = new CoursewareDataContext();
        private static readonly LanguagesRepository _langs = new LanguagesRepository(ref _context);
        private static readonly CoursesRepository _courses = new CoursesRepository(ref _context);

        [HttpGet]
        public ActionResult SelectLanguage()
        {
            ViewBag.Langs = Langs();
            return View();
        }

        // -------------------------------------------------------------------------------------------------------------------------------- //
        // ACTION SELECT LANGUAGE                                                                                                           //
        // -------------------------------------------------------------------------------------------------------------------------------- //
        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SelectLanguage(LanguageSelectViewModel model)
        {

            if (ModelState.IsValid)
            {
                return RedirectToAction("Index", new {language = model.Language});
            }
            else
            {
                ModelState.AddModelError("", Global.LanguageSelectError);
            }
            return View(model);
        } // ACTION SELECT LANGUAGE ENDS -------------------------------------------------------------------------------------------------- //

        /// <summary>
        /// 
        /// </summary>
        /// <param name="language"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index(Guid language)
        {
            var dbLangs = _courses.Get(language);
            var langs = dbLangs.Select(CourseViewModel.Transform).ToList();
            ViewBag.Language = language;
            return View(langs);
        } // METHOD INDEX ENDS ------------------------------------------------------------------------------------------------------------ // 



        /// <summary>
        /// 
        /// </summary>
        /// <param name="language"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create(Guid language)
        {
            var course = new CourseViewModel
            {
                Language = language,
                Id = Guid.NewGuid()
            };
            return View(course);
        } // METHOD CREATE ENDS ----------------------------------------------------------------------------------------------------------- //


        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(CourseViewModel model)
        {
            ActionResult result;
            if (ModelState.IsValid)
            {
               var c = _courses.Post(CourseViewModel.Transform(model));
                if (c != null && c.Id != Guid.Empty)
                {
                    result = RedirectToAction("Index", "Teachings", new {course = c.Id});
                } // IF ENDS
                else
                {
                    ModelState.AddModelError("", @Global.ErrorProcessingRequest);
                    result = View(model);
                } // ELSE ENDS
            } // IF ENDS
            else
            {
                result = View(model);
            }
            return result;
        } // METHOD CREATE ENDS ------------------------------------------------------------------------------------------------------------ //



        #region SELECTLISTS

        public JsonResult Langs()
        {
            var languages = _langs.Get();
            var languageItems =
                languages.Select(item => new SelectListItem
                {
                    Value = item.Id.ToString(),
                    Text = item.Title
                }).ToList();
            var deftlt = new SelectListItem
            {
                Value = "",
                Text = Global.Select,
                Selected = true
            };
            languageItems.Add(deftlt);
            languageItems.Reverse();
            return Json(languageItems, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

Org.Carfh.Courseware/Views/Courses/Create.cshtml
@using Lang
@model Org.Cafh.Courseware.Models.Courseware.CourseViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="headline-box3">
    <div class="headline-box-content">
        <h1>@Global.AddCourse</h1>
        <p class="lead"></p>
    </div>

</div>

<div class="platform-content">
    <div class="row">
        <div class="col-lg-12 content-form">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.Language)

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button onclick="window.history.back()" class="btn btn-default">@Global.Back</button>
                            <input type="submit" value="Create" class="btn btn-cafh-a"/>
                        </div>
                    </div>
                </div>
            }


        </div>

    </div>
</div>

Org.Carfh.Courseware/Views/Courses/Index.cshtml
@using Lang
@model IEnumerable<Org.Cafh.Courseware.Models.Courseware.CourseViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="headline-box3">
    <div class="headline-box-content">
        <h1>@Global.CourseCatalog</h1>
        <p class="lead">@Global.CourseCatalogDescription</p>
    </div>

</div>

<div class="platform-content">
    <div class="row">

        <div class="col-lg-12">
            <div class="teachings-actions">
                <a href="@Url.Action("Create", "Courses", new {language = ViewBag.Language})" class="btn btn-cafh-a"><i class="fa fa-plus"></i> @Global.Add</a>
            </div>
        </div>

        <div class="col-lg-12 content-form">

            @foreach (var item in Model)
            {

                <div class="col-lg-12 course">
                    <div class="col-lg-12 course-title">
                        <h4><strong>@Html.DisplayFor(modelItem => item.Title)</strong> </h4>
                    </div>
                    <div class="col-lg-12 course-desc">
                        <h4>@Global.Description</h4>

                        @Html.DisplayFor(modelItem => item.Description)
                        <hr/>
                        <div class="">
                            <a href="@Url.Action("Index", "Teachings", new {course = item.Id})" class="btn btn-cafh-a"> @Global.GoToTeachings <i class="fa fa-arrow-circle-right"></i></a>
                            <a href="@Url.Action("Delete", "Courses", new {course = item.Id})" class="btn btn-danger"> @Global.Delete <i class="fa fa-trash"></i></a>
                            <a href="@Url.Action("Edit", "Courses", new {course = item.Id})" class="btn btn-success"> @Global.Edit <i class="fa fa-pencil"></i></a>
                        </div>
                        <hr/>
                    </div>

                </div>

            }

        </div>
    </div>
</div>

Org.Carfh.Courseware/Views/Courses/SelectLanguage.cshtml
@using Lang
@model Org.Cafh.Courseware.Models.Courseware.LanguageSelectViewModel

@{
    ViewBag.Title = @Global.Language;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="headline-box2">
    <div class="headline-box-content">
        <h1>@Global.Language</h1>
    </div>
</div>

<div class="platform-content">
    <div class="row">
        <div class="col-lg-6">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>@Global.SelectLanguageInstructions</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select data-val="true" data-val-required="Please select a valid language." htmlattributes="{ class = form-control, id = Language }" id="Language" name="Language">
                               
                            </select>
                            @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="@Global.Next" class="btn btn-cafh-a" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>






@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="../../Scripts/courses.language.js"></script>
}